version: '3'

services:
  backend:
    build: backend
    restart: always
    volumes:
      - /opt/bored/backend/data:/opt/bored/backend/data

  frontend:
    build: frontend
    restart: always

  proxy:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8082:8080